### ISSUE TITLE
Maybe a stretch?

### ISSUE THREAD

**Issue by mlgvla** [learn-co-curriculum/phase-3-sequences#9] opened 2022-07-18 21:44 UTC
I'm a complete newbie to Python, but the only way I could pass the first test was to use the following code:

`  if length == 0:
        print('', end='')`
        
 In other words, the first test forces me to eliminate a "\n."  If that's intentional, then ok, but I found it a bit discouraging to have to do that much research in order to pass the first test.

**Comment by jlboba** [comment] 2022-07-22 18:13
Closing as duplicate of #7 and possibly resolved in https://github.com/learn-co-curriculum/phase-3-sequences/commit/dc052f25b46f7cd80131bdf6440a628600c6fb75 

If concern still persists, please open a new issue!

**Closed as completed by jlboba** 2022-07-22 18:13 UTC
Labels: se curriculum, se python
